export const Routes = {
	Home: "/",
	Login: "/login",
	SignUp: "/sign-up",
	Setup: "/setup",
	ResetPassword: "reset-password",
	Assistants: "assistants",
	Shop: "/shop",
	Friends: "/friends",
	Leaderboard: "/leaderboard",
	Settings: "/settings",
	Profile: "/profile",
	Help: "/help",
	NotFound: "/404",
};
